version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: annotation_db
      POSTGRES_USER: annotation_user
      POSTGRES_PASSWORD: annotation_password

  application_server:
    build:
      context: ./application_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./application_server:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  annotation_server:
    build:
      context: ./annotation_server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./annotation_server:/app
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db

volumes:
  postgres_data:
