version: "3.8"
services:
  annotation_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
    container_name: annotation_db
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    restart: unless-stopped
    tty: True

  annotation_app:
    build: .
    volumes:
      - ./:/annotation_app
    restart: unless-stopped
    ports:
      - "81:8000"
    image: annotation_app:latest
    container_name: annotation_app
    depends_on:
      - annotation_db
    tty: True
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
