# Generated by Django 3.2.18 on 2023-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='wikidata_explanations',
            field=models.TextField(blank=True),
        ),
    ]
