# Generated by Django 3.2.18 on 2023-06-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20230611_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
